services:
  api:
    image: alarms-api-image
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5293:80
    volumes:
      - alarms_api_data:/app/data
volumes:
  alarms_api_data: