services:
  api:
    image: alarms-api-image
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../db_data:/app/data
      - ./wwwroot:/app/wwwroot
